import simulation as sim
from protocols.normal import Normal
from protocols.letter_envelope import LetterEnvelope
import time

def run_all():
    normal_client_deauth()
    normal_ap_deauth()
    normal_ap_deauth_all()
    normal_attacker_client_deauth()
    normal_attacker_ap_deauth()
    normal_attacker_ap_deauth_all()
    envelope_client_deauth()
    normal_ap_deauth()
    envelope_ap_deauth_all()
    envelope_attacker_client_deauth()
    envelope_attacker_ap_deauth()
    envelope_attacker_ap_deauth_all()

def normal_client_deauth():
    ether = sim.Ether()
    protocol = Normal()
    ap = sim.AccessPoint(ether, "bo:ba:ca:fe:00:01", protocol, "AccessPoint")
    time.sleep(0.5)
    client = sim.Client(ether, "de:ad:be:ef:00:01", protocol)
    client.connect()
    time.sleep(0.5)
    assert(client.connected)
    client.deauth()
    time.sleep(0.5)
    assert(not ap.client_connected("de:ad:be:ef:00:01"))
    ap.stop()

def normal_ap_deauth():
    ether = sim.Ether()
    protocol = Normal()
    ap = sim.AccessPoint(ether, "bo:ba:ca:fe:00:01", protocol, "AccessPoint")
    time.sleep(0.5)
    client = sim.Client(ether, "de:ad:be:ef:00:01", protocol)
    client.connect()
    time.sleep(0.5)
    assert(client.connected)
    ap.deauth_client("de:ad:be:ef:00:01")
    time.sleep(0.5)
    assert(not client.connected)
    ap.stop()

def normal_ap_deauth_all():
    ether = sim.Ether()
    protocol = Normal()
    ap = sim.AccessPoint(ether, "bo:ba:ca:fe:00:01", protocol, "AccessPoint")
    time.sleep(0.5)
    client = sim.Client(ether, "de:ad:be:ef:00:01", protocol)
    client.connect()
    time.sleep(0.5)
    assert(client.connected)
    ap.deauth_all()
    time.sleep(0.5)
    assert(not client.connected)
    ap.stop()

def normal_attacker_client_deauth():
    ether = sim.Ether()
    protocol = Normal()
    ap = sim.AccessPoint(ether, "bo:ba:ca:fe:00:01", protocol, "AccessPoint")
    time.sleep(0.5)
    client = sim.Client(ether, "de:ad:be:ef:00:01", protocol)
    client.connect()
    time.sleep(0.5)
    assert(client.connected)
    ether.send(sim.Frame.deauth("de:ad:be:ef:00:01", "bo:ba:ca:fe:00:01", {}))
    time.sleep(0.5)
    assert(not ap.client_connected("de:ad:be:ef:00:01"))
    ap.stop()

def normal_attacker_ap_deauth():
    ether = sim.Ether()
    protocol = Normal()
    ap = sim.AccessPoint(ether, "bo:ba:ca:fe:00:01", protocol, "AccessPoint")
    time.sleep(0.5)
    client = sim.Client(ether, "de:ad:be:ef:00:01", protocol)
    client.connect()
    time.sleep(0.5)
    assert(client.connected)
    ether.send(sim.Frame.deauth("bo:ba:ca:fe:00:01", "de:ad:be:ef:00:01", {}))
    time.sleep(0.5)
    assert(not client.connected)
    ap.stop()

def normal_attacker_ap_deauth_all():
    ether = sim.Ether()
    protocol = Normal()
    ap = sim.AccessPoint(ether, "bo:ba:ca:fe:00:01", protocol, "AccessPoint")
    time.sleep(0.5)
    client = sim.Client(ether, "de:ad:be:ef:00:01", protocol)
    client.connect()
    time.sleep(0.5)
    assert(client.connected)
    ether.send(sim.Frame.deauth("bo:ba:ca:fe:00:01", sim.ADDRESS_BROADCAST, {}))
    time.sleep(0.5)
    assert(not client.connected)
    ap.stop()


# Letter envelope
def envelope_client_deauth():
    ether = sim.Ether()
    protocol = LetterEnvelope()
    ap = sim.AccessPoint(ether, "bo:ba:ca:fe:00:01", protocol, "AccessPoint")
    time.sleep(0.5)
    client = sim.Client(ether, "de:ad:be:ef:00:01", protocol)
    client.connect()
    time.sleep(0.5)
    assert(client.connected)
    client.deauth()
    time.sleep(0.5)
    assert(not ap.client_connected("de:ad:be:ef:00:01"))
    ap.stop()

def normal_ap_deauth():
    ether = sim.Ether()
    protocol = LetterEnvelope()
    ap = sim.AccessPoint(ether, "bo:ba:ca:fe:00:01", protocol, "AccessPoint")
    time.sleep(0.5)
    client = sim.Client(ether, "de:ad:be:ef:00:01", protocol)
    client.connect()
    time.sleep(0.5)
    assert(client.connected)
    ap.deauth_client("de:ad:be:ef:00:01")
    time.sleep(0.5)
    assert(not client.connected)
    ap.stop()

def envelope_ap_deauth_all():
    ether = sim.Ether()
    protocol = LetterEnvelope()
    ap = sim.AccessPoint(ether, "bo:ba:ca:fe:00:01", protocol, "AccessPoint")
    time.sleep(0.5)
    client = sim.Client(ether, "de:ad:be:ef:00:01", protocol)
    client.connect()
    time.sleep(0.5)
    assert(client.connected)
    ap.deauth_all()
    time.sleep(0.5)
    assert(not client.connected)
    ap.stop()

def envelope_attacker_client_deauth():
    ether = sim.Ether()
    protocol = LetterEnvelope()
    ap = sim.AccessPoint(ether, "bo:ba:ca:fe:00:01", protocol, "AccessPoint")
    time.sleep(0.5)
    client = sim.Client(ether, "de:ad:be:ef:00:01", protocol)
    client.connect()
    time.sleep(0.5)
    assert(client.connected)
    ether.send(sim.Frame.deauth("de:ad:be:ef:00:01", "bo:ba:ca:fe:00:01", {}))
    time.sleep(0.5)
    assert(ap.client_connected("de:ad:be:ef:00:01"))
    ap.stop()

def envelope_attacker_ap_deauth():
    ether = sim.Ether()
    protocol = LetterEnvelope()
    ap = sim.AccessPoint(ether, "bo:ba:ca:fe:00:01", protocol, "AccessPoint")
    time.sleep(0.5)
    client = sim.Client(ether, "de:ad:be:ef:00:01", protocol)
    client.connect()
    time.sleep(0.5)
    assert(client.connected)
    ether.send(sim.Frame.deauth("bo:ba:ca:fe:00:01", "de:ad:be:ef:00:01", {}))
    time.sleep(0.5)
    assert(client.connected)
    ap.stop()

def envelope_attacker_ap_deauth_all():
    ether = sim.Ether()
    protocol = LetterEnvelope()
    ap = sim.AccessPoint(ether, "bo:ba:ca:fe:00:01", protocol, "AccessPoint")
    time.sleep(0.5)
    client = sim.Client(ether, "de:ad:be:ef:00:01", protocol)
    client.connect()
    time.sleep(0.5)
    assert(client.connected)
    ether.send(sim.Frame.deauth("bo:ba:ca:fe:00:01", sim.ADDRESS_BROADCAST, {}))
    time.sleep(0.5)
    assert(client.connected)
    ap.stop()
